version: '3.3'
services:
  web:
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - db
    environment:
      - DB_URL=${DB_URL} # This will take the value from the .env file
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: